# Generated by Django 5.1.7 on 2025-03-22 14:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('starting_odometer', models.IntegerField(blank=True, null=True)),
                ('ending_odometer', models.IntegerField(blank=True, null=True)),
                ('total_driving_hours', models.FloatField(default=0)),
                ('total_on_duty_hours', models.FloatField(default=0)),
                ('total_off_duty_hours', models.FloatField(default=0)),
                ('total_sleeper_berth_hours', models.FloatField(default=0)),
                ('log_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_distance', models.FloatField(help_text='Total distance in miles')),
                ('estimated_driving_time', models.FloatField(help_text='Estimated driving time in hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_data', models.JSONField(help_text='Complete route data from mapping API')),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waypoint_type', models.CharField(choices=[('rest', 'Rest Stop'), ('fuel', 'Fuel Stop'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('overnight', 'Overnight Rest')], max_length=20)),
                ('sequence', models.IntegerField(help_text='Order in the route')),
                ('estimated_arrival', models.DateTimeField()),
                ('planned_duration', models.FloatField(help_text='Planned duration at this waypoint in hours')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On Duty Not Driving')], max_length=20)),
                ('activity', models.CharField(blank=True, help_text='Description of activity (loading, unloading, etc.)', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trip_planning.location')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('estimated_end_time', models.DateTimeField(blank=True, null=True)),
                ('current_cycle_hours', models.FloatField(help_text='Current cycle hours used (in hours)')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_trips', to='trip_planning.location')),
                ('dropoff_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_trips', to='trip_planning.location')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_trips', to='trip_planning.location')),
            ],
        ),
    ]
