# Generated by Django 5.0.1 on 2025-03-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_user_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
